add a `mod.nu` to `sugar completions`
This commit is here to avoid the following error introduced in
nushell/nushell#9185
```
Error: nu::parser::module_missing_mod_nu_file

  × Missing mod.nu file.
   ╭─[/nu-git-manager/src/sugar/mod.nu:1:1]
 1 │ export use completions
   ·            ─────┬─────
   ·                 ╰── module directory is missing a mod.nu file
   ╰────
  help: When importing a directory as a Nushell module, it needs to contain a mod.nu file (can be empty). Alternatively,
        you can use .nu files in the directory as modules individually.
```